### ISSUE TITLE
Generated code doesn't work with LicenseToCIL 1.0.0

### ISSUE THREAD

**Issue by marklam** [rspeele/Rezoom.SQL#38]
Following the tutorial in a .net 4.7.2 console app with FSharp.Core 4.5, the generated code produces an exception
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Rezoom.SQL.Mapping.CodeGeneration.ReaderTemplate`1' threw an exception.
  Source=Rezoom.SQL.Mapping
  StackTrace:
   at Rezoom.SQL.Mapping.CodeGeneration.ReaderTemplate`1.Template()
   at Rezoom.SQL.Compiler.BackendUtilities.DefaultMigrationBackend.GetMigrationsRun()
   at Rezoom.SQL.Migrations.MigrationUtilities.runMigrations(MigrationConfig config, IMigrationBackend backend, IEnumerable`1 migrationTrees)
   at Rezoom.SQL.Migrations.MigrationExtensions.Run(MigrationTree`1[] migrations, MigrationConfig config, FSharpFunc`2 backend)
   at Program.MyModel.Migrate(MigrationConfig config)
   at Program.migrate()
   at Program.main(String[] argv)

Inner Exception 1:
MissingMethodException: Method not found: 'Microsoft.FSharp.Core.FSharpFunc`2<S`1<!!0>,Microsoft.FSharp.Core.FSharpFunc`2<LicenseToCIL.IL,S`1<S`1<!!1>>>> LicenseToCIL.Ops.newobj'x(System.Reflection.ConstructorInfo)'.

```
It seems to be a problem with the LicenseToCIL dependency, because pinning at 0.3.0 fixes it.

**Comment by rspeele** [comment]
Same underlying issue as #37.

**Comment by rspeele** [comment]
Closed by upgrading all to netstandard2/net10
